
services:

  # POSTGRESQL
  automotive_selection_db_postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - backend




  adminer:
    container_name: adminer_db
    restart: always
    build: .
    ports:
      - '8080:8080'
    networks:
      - backend

networks:
  backend:
volumes:
  postgres:
