
services:

  # POSTGRESQL
  automotive_selection_db_postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - backend




  adminer:
    container_name: adminer_db
    restart: always
    build: .
    ports:
      - '8080:8080'
    networks:
      - backend
      - frontend

  client:
    container_name: client
    restart: always
    image: automotive_selection_front
    build:
      context: ../automotive_selection_front/
      dockerfile: ../automotive_selection_front/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:80 # Map the exposed port 80 on the container to port 3000 on the host machine
    depends_on:
      - adminer
    networks:
      - frontend

networks:
  backend:
  frontend:
volumes:
  postgres:
