
##################### SPRING GLOBAL #################################
spring:
  ##################### DATA SOURCE #################################
  datasource:
    driver-class-name: org.postgresql.Driver
    #initialization-mode: always
    ##################### MY SQL DATABASE #################################
    url: jdbc:postgresql://localhost:5432/automotive_selection
    #url: jdbc:postgresql://automotive_selection_db_postgres:5432/automotive_selection
    #username: automotive_selection_app
    #password: automotive_selection_pw
    username: postgres
    password: admin
  ##################### JPA USED SPRING DATA #################################
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  ##################### SPRING MAIL PROPERTIES #################################
  mail:
    host: smtp.gmail.com
    port: 587
    username: dmtrpnchk@gmail.com
    password: pnchkdmtr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


####################### SECURITY ############################
security-token-app:
  auth:
    accessTokenSecret: secretKey
    accessTokenExpirationMsec: 30000000 #60000=one minute; remove one 0 and show tokes death

    refreshTokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    refreshTokenExpirationMsec: 120000000 #one minute; remove one 0 and show tokes death

AWS_ACCESS_KEY: AKIA5SEBSOS4NAU5PEW4
AWS_SECRET_KEY: 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
