spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/automotive_selection
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: dmtrpnchk@gmail.com
    password: pnchkdmtr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security-token-app:
  auth:
    accessTokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    accessTokenExpirationMsec: 60000000 #60000=one minute; remove one 0 and show tokes death

    refreshTokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    refreshTokenExpirationMsec: 120000000 #one minute; remove one 0 and show tokes death

admin:
  name: admin
  login: master
  password: master
  email: admin@gmail.com
  enabled: true
scheduler:
  admin:
    adminVerification:
      fixedRateMs: 10000